// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1Qk2s4yA3YF8Q98AMkLKMyI61YQjTmKM',
    appId: '1:742125653370:web:4de810eb84d4c597319ac3',
    messagingSenderId: '742125653370',
    projectId: 'scan-sense-d7ad9',
    authDomain: 'scan-sense-d7ad9.firebaseapp.com',
    storageBucket: 'scan-sense-d7ad9.appspot.com',
    measurementId: 'G-28HS1G3ZSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBoRPsAg2apxOW0oZ2FCExgRqfYfJxjaw',
    appId: '1:742125653370:android:df3013ce5873439f319ac3',
    messagingSenderId: '742125653370',
    projectId: 'scan-sense-d7ad9',
    storageBucket: 'scan-sense-d7ad9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6mBX3vq5tvmzzRZsYUN7qk0bJ8XiPvQQ',
    appId: '1:742125653370:ios:f7be352515532fd8319ac3',
    messagingSenderId: '742125653370',
    projectId: 'scan-sense-d7ad9',
    storageBucket: 'scan-sense-d7ad9.appspot.com',
    iosBundleId: 'com.example.scanSense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6mBX3vq5tvmzzRZsYUN7qk0bJ8XiPvQQ',
    appId: '1:742125653370:ios:4b553200b099766d319ac3',
    messagingSenderId: '742125653370',
    projectId: 'scan-sense-d7ad9',
    storageBucket: 'scan-sense-d7ad9.appspot.com',
    iosBundleId: 'com.example.scanSense.RunnerTests',
  );
}
