// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi1e0quYexdGAuiyUkrlR8hmXN0Str2hc',
    appId: '1:572499325891:web:74861a742f616ca971c376',
    messagingSenderId: '572499325891',
    projectId: 'scan-sense',
    authDomain: 'scan-sense.firebaseapp.com',
    storageBucket: 'scan-sense.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAslMVuIfJrltTc_wDX7Fz7nuLk_256zdU',
    appId: '1:572499325891:android:713075c6d17cfda871c376',
    messagingSenderId: '572499325891',
    projectId: 'scan-sense',
    storageBucket: 'scan-sense.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLNlWOcvEX8VLoXzKS7PoZCFM_FDeeoWU',
    appId: '1:572499325891:ios:3d6535fb6229586a71c376',
    messagingSenderId: '572499325891',
    projectId: 'scan-sense',
    storageBucket: 'scan-sense.appspot.com',
    iosBundleId: 'com.example.scanSense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLNlWOcvEX8VLoXzKS7PoZCFM_FDeeoWU',
    appId: '1:572499325891:ios:f8633334294d1d3071c376',
    messagingSenderId: '572499325891',
    projectId: 'scan-sense',
    storageBucket: 'scan-sense.appspot.com',
    iosBundleId: 'com.example.scanSense.RunnerTests',
  );
}
